In [1]:
%reload_ext postcell
%postcell register

PostCell loaded
Loading config file from /Users/reecevdw/UChicago/FINM 324/FINM324/postcell.conf
Registered user Reece_VanDeWeghe at https://postcell.io/post_cell

# Pandas Series - an overview

Pandas library provides a fantastic interface to tabular data, made up of rows and columns. This is usually used to represent "business" datasets such as customer or product information. Generally, tables are organized so rows represent observations and columns represent features. Such "tabular" datasets are different from other datasets used in machine learning, such as images, videos, graphs, etc.

We will study three main objects within the Pandas library: Dataframes and two objects which make up dataframes, Series and Indexes.

![](images/dataframes.jpg)

*Hint* Review earlier lectures which provide quickstart introductions to Numpy and Pandas. These notes take a more systematic approach to describing Pandas.

In [2]:
import numpy as np
import pandas as pd

In [3]:
pd.__version__

'2.2.3'

# Series

Pandas series are similar to Python's built-in lists and numpy arrays. Here is an example:

In [4]:
#Python list
["Bart", "Homer", "Lisa", "Maggie", "Marge"]

['Bart', 'Homer', 'Lisa', 'Maggie', 'Marge']

In [5]:
pd.Series(["Bart", "Homer", "Lisa", "Maggie", "Marge"])

0      Bart
1     Homer
2      Lisa
3    Maggie
4     Marge
dtype: object

In [6]:
#Numpy array
np.array(["Bart", "Homer", "Lisa", "Maggie", "Marge"])

array(['Bart', 'Homer', 'Lisa', 'Maggie', 'Marge'], dtype='<U6')

#### Series, like Numpy arrays, have types

In [ ]:
type([1, 2, 3])

In [ ]:
type([1.2, 2, 3])

In [ ]:
type([1.2, 2, "Home"])

In [ ]:
pd.Series([1, 2, 3])

In [ ]:
pd.Series([1.2, 2, 3])

In [ ]:
pd.Series([1.2, 2, "Homer"])

In [ ]:
pd.Series(["Marge", "Lisa", "Homer"])

Notice that, unlike Python lists, Series objects have types associated with them. One of the reasons Pandas and Numpy are so much faster than native Python is because all elements are expected to be the same type and can be optimized for performance.

**String type** With Pandas 1.0, string series have their own data type, while `object` will be the generic, catch all type.

**Exercise** Create a Pandas series, containing numbers from zero to 10

In [8]:
%%postcell exercise_030_110_a

pd.Series([41,24])
#type your answer here

Cell posted for evaluation

0    41
1    24
dtype: int64

#### Explicit data types and categorical data

There are times when you want control the type explicitely

In [ ]:
pd.Series([1, 2, 3, 4, 5])

In [ ]:
pd.Series([1, 2, 3, 4, 5], dtype="float64")

In [ ]:
pd.Series([1, 2, 3, 4, 5]).astype('float')

A much more useful usecase is when you want to force a column as categorical

In [ ]:
pd.Series(["Homer", "Marge", "Homer", "Homer", "Maggie", "Lisa"], dtype='category')

In [ ]:
pd.Series(["Homer", "Marge", "Homer", "Homer", "Maggie", "Lisa"]).astype('category')

In [ ]:
pd.Categorical(["Homer", "Marge", "Homer", "Homer", "Maggie", "Lisa", ]
           , categories=["Homer", "Marge", "Maggie", "Lisa"], ordered=False)

#### More complex keys

Notice that Pandas series are nothing more than a wrapper around Numpy arrays (at least in Pandas 1.0):

In [ ]:
ss = pd.Series(["Bart", "Homer", "Lisa", "Maggie", "Marge"])
ss

In [ ]:
ss.values

In [ ]:
ss.index

In [ ]:
type(ss.values)

In [ ]:
type(ss.index)

In [ ]:
type(np.array(["Bart", "Homer", "Lisa", "Maggie", "Marge"]))

Recall that Numpy was created to be a library for numeric matrix manipulation. It make sense to ask, what is the value at index zero. It makes no sense, in matrix math, to ask, "what is the value at index 'Homer'?"

Pandas, however, is designed to work with datasets which may have categories and texts. If a matrix contains ages of people, it is perfectly reasonable to ask, what is the 'age' value at index 'Homer.'

In [ ]:
ss

In [ ]:
ss[1]

In [ ]:
pd.Series([12, 38, 10, 2, 36])

In [112]:
ss2 = pd.Series([12, 38, 10, 2, 36], index=["Bart", "Homer", "Lisa", "Maggie", "Marge"])
ss2

Bart      12
Homer     38
Lisa      10
Maggie     2
Marge     36
dtype: int64

Notice that Series provide the ability to add a custom `index`:

In [ ]:
ss2["Homer"]

**Exercise** Create a series of ages and names of characters as the index:
Ned 41, Daenerys 16, Tyrion 32, Jon 16

In [10]:
%%postcell exercise_030_110_b

#type your answer here

Cell posted for evaluation

#### Series combine the properties of lists and dictionaries

In [ ]:
pd.Series([41, 16, 32, 16])

In [ ]:
pd.Series({'Ned': 41, 'Daenerys': 16, 'Tyrion': 32, 'Jon': 16})

Recall that Python's core lists are accessed by zero based integer values. Elements in a list are ordered, which means we can use the _slice_ notation to access multiple items:

In [20]:
["Bart", "Homer", "Lisa", "Maggie", "Marge"][2:4]

['Lisa', 'Maggie']

Dictionaries let us provide our own keys. However, they cannot be sliced:

In [ ]:
{"Homer":38, "Marge":36, "Bart":12, "Lisa":10, "Maggie":6}["Bart":"Maggie"] #<= dictionaries don't understand slicing

Pandas Series combine properties of lists and dictionaries, along with the performance of Numpy:

In [11]:
ss2

Bart      12
Homer     38
Lisa      10
Maggie     2
Marge     36
dtype: int64

In [12]:
ss2["Bart"] #as dictionary

np.int64(12)

In [17]:
ss2[0] # as list

# ss2.iloc[0]

/var/folders/7k/8z_vjlk54rx1s36kpkcllkfr0000gn/T/ipykernel_34135/1878363338.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ss2[0] # as list

np.int64(12)

In [18]:
ss2[2:4] # as list

Lisa      10
Maggie     2
dtype: int64

In [19]:
ss2["Lisa":"Marge"] # as ??

Lisa      10
Maggie     2
Marge     36
dtype: int64

**Caveat** Notice that when we used slicing with the implicit (built-in) index values: `2:4`, the 4th value wasn't included in the result set (as expected). However, when sliced with explicit index values (the index we provided): "Bart":"Maggie", the last value _is_ included. Series provides a way around this confusion via `.loc` and `.iloc`

![](images/series.jpg)

In [ ]:
ss2

In [ ]:
ss2.values

In [ ]:
ss2.index

### Caveat: `s.columnA` vs `s['columnA']`

So far, we have accessed elements of Series using the syntax `s['columnA']`. However, the following syntax is also allowed `s.columnA`. For example

In [ ]:
ss2

In [ ]:
ss2['Marge']

In [ ]:
ss2.Marge

In [ ]:
ss2.

In [ ]:
ss2.shape

In [ ]:
ss2.Mr. Burns

The 'dot' syntax is very convenient, since it looks like calling a normal method on an object. It is slightly shorter to type and prvides better IDE help. In a cell, type `ss2.` then press the [TAB] key. You will notice a list of dropdowns. Type "M" and you will see Marge and Maggie's name pop up. You are using the autocomplete to find elements of a series!

Also notice that you can call actual operations on a series:

In [ ]:
ss2.sum()

If you type `series.XYZ` .. is that referring to an element, indexed by the key "XYZ" or is it referring to the function "XYZ()"? This is confusion is the reason why, unless we are sure that there is no conflict, the safer option is to use the syntax `s['columnA']`

In [ ]:
ss2['Homer J']
ss.Homer J #<= syntax error!

### Indexing Series

Similar to Numpy, values in series can be retrieved in several ways:
1. Implicit index (similar to lists)
2. Explicit index or label (similar to dictionaries)
3. Slicing
4. Boolean Masking
5. Fancy indexing

#### Implicit index

In [ ]:
ss2

Given the series above, where names of the Simpson family are the index and their ages are the values, we can get Marge's age, which is at row 5 via directly requesting the second value (remember that Python is zero based):

In [ ]:
ss2[4]

**Exercise** Given the series `ss2`, get second element

In [21]:
%%postcell exercise_030_110_c

ss2.iloc[1]

#type your answer here

Cell posted for evaluation

np.int64(38)

#### Explicit index or labels

Much like dictionaries, the key associated with Marge's name will return her age:

In [ ]:
ss2

In [ ]:
ss2["Marge"]

**Caveat** Notice that the same syntax is being used to access data implicitely and explicitely: `series[index]`. If `index` is an integer, then Pandas assumes it is an implicit inex, if it is not an integer, then Pandas assumes it is an explicit index. What if our explicit index was also an intger? See `.loc` and `.iloc`, later in the lecture

**Exercise** Given the series `ss2`, get the element corresponding to "Maggie"

In [22]:
%%postcell exercise_030_110_d

ss2["Maggie"]

#type your answer here

Cell posted for evaluation

np.int64(2)

#### Slicing

Similar to Numpy arrays and Python lists, Series can be sliced. Note that keys are sliced in terms of their location in the series, **not alphabetically**

In [ ]:
ss2

In [ ]:
ss2[2:4]

In [ ]:
ss2["Lisa":"Marge"]

Notice that slicing with explicit values includes the last item while slicing with implicit indexes the last value is not included.

Remember that negative indexes can be used, just like normal Python lists. Below we select items which start at "second to last" and end at the last item:

In [ ]:
ss2

In [ ]:
ss2[-2:]

**Exercise** Given the series `ss2`, get the second, third and fourth elements (use slicing)

In [24]:
%%postcell exercise_030_110_e

ss2[1:4]

#type your answer here

Cell posted for evaluation

Homer     38
Lisa      10
Maggie     2
dtype: int64

#### Boolean (Masking)

Providing a `True` or `False` value for element results in elements corresponding to `False` being filtered out.

In [25]:
ss2

Bart      12
Homer     38
Lisa      10
Maggie     2
Marge     36
dtype: int64

In [26]:
mask = [True, False, True, True, True]
ss2[mask]

Bart      12
Lisa      10
Maggie     2
Marge     36
dtype: int64

In [27]:
ss2[[True, False, True, True, True]]

Bart      12
Lisa      10
Maggie     2
Marge     36
dtype: int64

Btw, this does not work with Python lists

In [28]:
['B', 'H', 'L', 'M', 'M'][mask]

TypeError: list indices must be integers or slices, not list

Filter on the index

In [29]:
ss2.index != "Homer"

array([ True, False,  True,  True,  True])

In [30]:
ss2[ss2.index != "Homer"]

Bart      12
Lisa      10
Maggie     2
Marge     36
dtype: int64

In [31]:
ss2[ss2 != "Homer"]

Bart      12
Homer     38
Lisa      10
Maggie     2
Marge     36
dtype: int64

Filter on the values

In [32]:
ss2.values <30

array([ True, False,  True,  True, False])

In [33]:
ss2[ss2.values < 30]

Bart      12
Lisa      10
Maggie     2
dtype: int64

In [34]:
ss2 < 30

Bart       True
Homer     False
Lisa       True
Maggie     True
Marge     False
dtype: bool

Notice that you don't have to call `.values` for cleaner code

In [35]:
ss2[ss2 < 30]

Bart      12
Lisa      10
Maggie     2
dtype: int64

**Exercise** Find everyone older than 2 years

In [36]:
%%postcell exercise_030_110_f

ss2[ss2 > 2]

#type your answer here

Cell posted for evaluation

Bart     12
Homer    38
Lisa     10
Marge    36
dtype: int64

**Exercise** Find everyone, except "Maggie"

In [38]:
%%postcell exercise_030_110_g

ss2[ss2.index != "Maggie"]

#type your answer here

Cell posted for evaluation

Bart     12
Homer    38
Lisa     10
Marge    36
dtype: int64

#### Fancy indexing

If you know the specific list of items, you can ask the Series to return them directly:

In [39]:
ss2

Bart      12
Homer     38
Lisa      10
Maggie     2
Marge     36
dtype: int64

In [41]:
# ss2[[1,3,4]]

ss2.iloc[[1,3,4]]

Homer     38
Maggie     2
Marge     36
dtype: int64

Notice that the order of elements in the index will be what the Series returns:

In [44]:
ss2[[4,3,1]]

/var/folders/7k/8z_vjlk54rx1s36kpkcllkfr0000gn/T/ipykernel_34135/162589300.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ss2[[4,3,1]]

Marge     36
Maggie     2
Homer     38
dtype: int64

In [43]:
ss2[[4,3,2, 2, 2, 2]]

/var/folders/7k/8z_vjlk54rx1s36kpkcllkfr0000gn/T/ipykernel_34135/1556507491.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ss2[[4,3,2, 2, 2, 2]]

Marge     36
Maggie     2
Lisa      10
Lisa      10
Lisa      10
Lisa      10
dtype: int64

You can also use the explicit index, instead of the implicit index

In [42]:
ss2[["Marge", "Marge", "Lisa"]]

Marge    36
Marge    36
Lisa     10
dtype: int64

**Exercise** Given the series `ss2`, get the second, third and fifth elements (using fancy indexing)

In [45]:
%%postcell exercise_030_110_h


ss2.iloc[[1,2,4]]

#type your answer here

Cell posted for evaluation

Homer    38
Lisa     10
Marge    36
dtype: int64

### `.loc` and `.iloc` or confusion when explicit indexes are integers

Notice that the series we have been working with has strings as the explicit index and integers as the values:

In [46]:
pd.Series([12, 38, 10, 2, 36], index=["Bart", "Homer", "Lisa", "Maggie", "Marge"])

Bart      12
Homer     38
Lisa      10
Maggie     2
Marge     36
dtype: int64

What if we flip that around and a couple more characters

In [47]:
ss3 = pd.Series(["Bart", "Homer", "Lisa", "Maggie", "Marge"], index=[12, 38, 10, 2, 36])
ss3

12      Bart
38     Homer
10      Lisa
2     Maggie
36     Marge
dtype: object

**Caveat** If I ask for values for 1 `ss3[2]`, am I asking for elements at location 2 or for characters with age 2?

In [50]:
ss3[2]

'Maggie'

In order to avoid this confusion, Pandas provides methods `.loc`, which expects explicit index values (aka labels) and `.iloc`, which expects implicit index values:

In [51]:
ss3.iloc[2]

'Lisa'

In [52]:
ss3.loc[2]

'Maggie'

#### Special indexer: `.at[]`

Implicit index (similar to lists)
Explicit index (similar to dictionaries)
Slicing
Masking
Fancy indexing

Notice that we have several ways of accessing elements: index, labels, slicing, masking and fancy indexing. The same syntax `s[XXX]`, `s.loc[XXX]` or `s.iloc[XXX]` can be used with any of the methods above. There are times when you want exactly a single, scalar value to be returned. In such cases, you use the syntax `s.at[XXX]`:

In [53]:
ss3.at[2]

'Maggie'

In [54]:
ss2.at['Maggie']

np.int64(2)

In [ ]:
ss3.at[1:2] # <= slicing is prohibited, since it would return multiple values

### Indexing summary

In [55]:
ss2

Bart      12
Homer     38
Lisa      10
Maggie     2
Marge     36
dtype: int64

```python
#implicit (like lists)
ss2[integer] # get value at location number

#explicit labels (like dictionaries)
ss2[key]     # get value at index key 

#slicing
ss2[integer_start:integer_end] # get values between locations integer_start and integer_end (integer_end not included)
ss2[key_start:key_end]         # get values between keys key_start and key_end (key_end INCLUDED, by locations of keys, not alaphabetical)

#fancy indexing
ss2[[integer1, intger3]]  # get values at locations intger1 and integer3
ss2[[key1, key3]] # get values at keys key1 and key3

ss2.loc[...]  # always operate in terms of keys

ss2.iloc[...] # always operate in terms of location

ss2.at[...]   # always return a single value
```

### Creating Series

We have already seen series being create with a list and an index: `pd.Series(data, index=None)`.

Another common way of creating a series is via a dictionary:

In [ ]:
pd.Series({"Homer":38, "Marge":36})

Create it from a list

In [ ]:
pd.Series(['Homer', 'Marge', "Maggie"])

There are less common metods of creating series, such as:

In [ ]:
pd.Series(44, index=["Homer", "Marge", "Maggie"])

You can always combine what you learned for lists with series:

### Converting to other formats

Series can be converted to a dictionary very easily:

In [56]:
ss2

Bart      12
Homer     38
Lisa      10
Maggie     2
Marge     36
dtype: int64

In [57]:
ss2.to_dict()

{'Bart': 12, 'Homer': 38, 'Lisa': 10, 'Maggie': 2, 'Marge': 36}

Other, similar method:
1. ss2.to_excel
2. ss2.to_frame (conver to dataframe)
3. ss2.to_json
4. ss2.to_sql

Any many others

You often need to convert a series to a DataFrame:

In [58]:
ss2

Bart      12
Homer     38
Lisa      10
Maggie     2
Marge     36
dtype: int64

In [59]:
ss2.to_frame()

         0
Bart    12
Homer   38
Lisa    10
Maggie   2
Marge   36

In [60]:
pd.DataFrame(ss2)

         0
Bart    12
Homer   38
Lisa    10
Maggie   2
Marge   36

In [61]:
pd.DataFrame(ss2).shape

(5, 1)

One of the most useful patterns is to convert a series and its index to a dataframe with two columns:

In [62]:
ss2

Bart      12
Homer     38
Lisa      10
Maggie     2
Marge     36
dtype: int64

In [ ]:
ss2.reset_index(name="age")

In [ ]:
ss2.reset_index(name="age").rename(columns={"index":"name"})

### Operating on series

Much like Numpy arrays, several operations can be done on a series:

In [63]:
ss2

Bart      12
Homer     38
Lisa      10
Maggie     2
Marge     36
dtype: int64

In [68]:
ss2.sum(), ss2.count(), ss2.min(), ss2.max(), ss2.mean()

(np.int64(98), np.int64(5), 2, 38, np.float64(19.6))

In [69]:
# For each VALUE in the series, is it in this list?
ss2.isin([10, 13, 12, 46, 38])

Bart       True
Homer      True
Lisa       True
Maggie    False
Marge     False
dtype: bool

In [70]:
ss2.isin(["Homer", "Mr. Burns", "Barney", "Maggie", "Dr. Hibert"])

Bart      False
Homer     False
Lisa      False
Maggie    False
Marge     False
dtype: bool

In [71]:
ss2.index.isin(["Homer", "Mr. Burns", "Barney", "Maggie", "Dr. Hibert"])

array([False,  True, False,  True, False])

In [73]:
ss2.index

Index(['Bart', 'Homer', 'Lisa', 'Maggie', 'Marge'], dtype='object')

**Exercise** Explain the previous two cells

In [74]:
ss2

Bart      12
Homer     38
Lisa      10
Maggie     2
Marge     36
dtype: int64

In [88]:
ss2.sample(2)

Maggie     2
Marge     36
dtype: int64

In [89]:
ss2.sample(10, replace=True)

Homer     38
Lisa      10
Bart      12
Bart      12
Homer     38
Maggie     2
Bart      12
Lisa      10
Bart      12
Bart      12
dtype: int64

In [90]:
ss2.nlargest(2)

Homer    38
Marge    36
dtype: int64

In [91]:
ss2.astype('float')

Bart      12.0
Homer     38.0
Lisa      10.0
Maggie     2.0
Marge     36.0
dtype: float64

In [95]:
ss2.sort_values()

Maggie     2
Lisa      10
Bart      12
Marge     36
Homer     38
dtype: int64

In [93]:
ss2.sort_index()

Bart      12
Homer     38
Lisa      10
Maggie     2
Marge     36
dtype: int64

In [110]:
ss2

Bart      22
Homer     48
Lisa      20
Maggie    12
Marge     46
dtype: int64

**Exercise** Add two years to everyone's age (recall the Numpy lecture) in series `ss2`

In [118]:
%%postcell exercise_030_110_i

ss2 + 2

#type your answer here

Cell posted for evaluation

Bart      14
Homer     40
Lisa      12
Maggie     4
Marge     38
dtype: int64

### Combining series and intelligently handling missing data

The ability to intelligenty combine series is one of the most powerful features of Pandas. Note the series we have already been working on, which contains Simpson family ages:

In [119]:
ss2

Bart      12
Homer     38
Lisa      10
Maggie     2
Marge     36
dtype: int64

In [120]:
weights = pd.Series([240, 85], index=["Homer", "Bart"])
weights

Homer    240
Bart      85
dtype: int64

Notice that we don't have everyone's weight. What happens when we combine these two series:

In [121]:
pd.DataFrame({'ages':ss2, 'weights':weights})

        ages  weights
Bart      12     85.0
Homer     38    240.0
Lisa      10      NaN
Maggie     2      NaN
Marge     36      NaN

Series are designed for single dimensional data. DataFrames, which we will study soon, contain multiple series. Notice that the two series have been intelligently combined!

Let's add two series. Notice that we can add them as if they were scalars or numpy arrays. Further notice that Pandas intelligently inserts `NaN` in appropriate places

In [122]:
ss2 + weights

Bart       97.0
Homer     278.0
Lisa        NaN
Maggie      NaN
Marge       NaN
dtype: float64

In [123]:
ss2.add(weights, fill_value=0)

Bart       97.0
Homer     278.0
Lisa       10.0
Maggie      2.0
Marge      36.0
dtype: float64

**Intelligent handling of missing values is one of the reasons to use Pandas**

Note that aggregate functions _know_ to ignore missing values when adding series:

In [124]:
(ss2 + weights).sum()

np.float64(375.0)

In [ ]:
97+278