In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
%reload_ext postcell
%postcell register

PostCell loaded
Loading config file from /Users/reecevdw/UChicago/FINM 324/FINM324/postcell.conf
Registered user Reece_VanDeWeghe at https://postcell.io/post_cell

In [3]:
%matplotlib inline

#### Generating sample data

In [4]:
#boiler plate code
student_scores_pd = pd.DataFrame(((np.random.rand(10,4) * 100) )
             , columns=['Assignment 1', 'Assignment 2', 'Test', 'Extra Credit']
             , index=['Homer', 'Marge', 'Bart', 'Lisa', 'Maggie', 'Jon', 'Arya', 'Ned', 'Danny', 'That red lady']
            )
student_scores_pd['Test'] *= 10
#student_scores_pd['Test2'] = 'hello'
student_scores_pd['Extra Credit'] = np.power(student_scores_pd['Extra Credit'], 2)/100
student_scores_pd = student_scores_pd.round()

student_scores_pd

               Assignment 1  Assignment 2   Test  Extra Credit
Homer                  67.0          68.0   86.0           1.0
Marge                  17.0          78.0  101.0           9.0
Bart                   38.0          41.0  442.0          34.0
Lisa                   44.0          93.0  504.0          70.0
Maggie                 16.0          18.0   35.0           1.0
Jon                    35.0          11.0  142.0           8.0
Arya                   33.0          94.0  988.0          49.0
Ned                    33.0          97.0  381.0           4.0
Danny                   9.0           2.0  621.0          86.0
That red lady          53.0           9.0  361.0          51.0

# Pandas - dataframe operations

Much like series (and numpy), dataframes have _many_ built in mathematical operations. Calling an aggregating math function on a dataframe will return values, aggregated for each column:

In [8]:
student_scores_pd.to_numpy().sum()

np.float64(4830.0)

In [6]:
student_scores_pd.sum()

Assignment 1     345.0
Assignment 2     511.0
Test            3661.0
Extra Credit     313.0
dtype: float64

However, if you wanted to add up the two assignments and the test for each student, you would have to tell the sum function that you want to sum across a different axis:

In [11]:
student_scores_pd.sum(axis=1)

Homer             222.0
Marge             205.0
Bart              555.0
Lisa              711.0
Maggie             70.0
Jon               196.0
Arya             1164.0
Ned               515.0
Danny             718.0
That red lady     474.0
dtype: float64

In [12]:
student_scores_pd.sum(axis='columns')

Homer             222.0
Marge             205.0
Bart              555.0
Lisa              711.0
Maggie             70.0
Jon               196.0
Arya             1164.0
Ned               515.0
Danny             718.0
That red lady     474.0
dtype: float64

In [13]:
student_scores_pd.sum(axis='rows')

Assignment 1     345.0
Assignment 2     511.0
Test            3661.0
Extra Credit     313.0
dtype: float64

#### Detour: `...axis=?`

`axis=0` = `axis="rows"` and `axis=1` = `axis="columns"` . 

This is the rule which helps me the most:

`df.sum(axis='rows')` means you end up with value for each **column**

`df.sum(axis='columns')` means you end up with value for each **row**


Note that the default axis in Pandas functions is 0 or 'rows'. This means that, by default, functions will operate on rows or _go through each column_ , which will result in _one value per column_.

In [ ]:
student_scores_pd.mean()

In [ ]:
student_scores_pd.mean(axis=0)

In [ ]:
student_scores_pd.mean(axis='rows')

### Remove columns (and the 'axis' error related to it)

In [14]:
student_scores_pd

               Assignment 1  Assignment 2   Test  Extra Credit
Homer                  67.0          68.0   86.0           1.0
Marge                  17.0          78.0  101.0           9.0
Bart                   38.0          41.0  442.0          34.0
Lisa                   44.0          93.0  504.0          70.0
Maggie                 16.0          18.0   35.0           1.0
Jon                    35.0          11.0  142.0           8.0
Arya                   33.0          94.0  988.0          49.0
Ned                    33.0          97.0  381.0           4.0
Danny                   9.0           2.0  621.0          86.0
That red lady          53.0           9.0  361.0          51.0

In [15]:
student_scores_pd.drop(['Test'])

KeyError: "['Test'] not found in axis"

In [16]:
student_scores_pd.drop(['Test'], axis=1)

               Assignment 1  Assignment 2  Extra Credit
Homer                  67.0          68.0           1.0
Marge                  17.0          78.0           9.0
Bart                   38.0          41.0          34.0
Lisa                   44.0          93.0          70.0
Maggie                 16.0          18.0           1.0
Jon                    35.0          11.0           8.0
Arya                   33.0          94.0          49.0
Ned                    33.0          97.0           4.0
Danny                   9.0           2.0          86.0
That red lady          53.0           9.0          51.0

Most functions don't _mutate_ or change the original dataframe (unless you use the `inplace=True` argument):

In [17]:
student_scores_pd.drop(columns='Test')

               Assignment 1  Assignment 2  Extra Credit
Homer                  67.0          68.0           1.0
Marge                  17.0          78.0           9.0
Bart                   38.0          41.0          34.0
Lisa                   44.0          93.0          70.0
Maggie                 16.0          18.0           1.0
Jon                    35.0          11.0           8.0
Arya                   33.0          94.0          49.0
Ned                    33.0          97.0           4.0
Danny                   9.0           2.0          86.0
That red lady          53.0           9.0          51.0

In [18]:
student_scores_pd

               Assignment 1  Assignment 2   Test  Extra Credit
Homer                  67.0          68.0   86.0           1.0
Marge                  17.0          78.0  101.0           9.0
Bart                   38.0          41.0  442.0          34.0
Lisa                   44.0          93.0  504.0          70.0
Maggie                 16.0          18.0   35.0           1.0
Jon                    35.0          11.0  142.0           8.0
Arya                   33.0          94.0  988.0          49.0
Ned                    33.0          97.0  381.0           4.0
Danny                   9.0           2.0  621.0          86.0
That red lady          53.0           9.0  361.0          51.0

```python
student_scores_pd.drop(['Test'], axis=1, inplace=True)

student_scores_pd = student_scores_pd.drop(['Test'], axis=1)

```

In [21]:
from sklearn.linear_model import LinearRegression

# model.fit(df.drop(columns='Test'), df['Test'])

model = LinearRegression()

model.fit(student_scores_pd.drop(columns='Test'), student_scores_pd['Test'])

LinearRegression()

### Common mathematical functions

Pandas has all the standard mathematical and statistical functions you might expect to find in a data science package such as `mean`, `sum`, `max`, `min`, `log`, etc.

**Example** Given the `student_scores_pd` dataframe below, standardize it so all values are between 0 and 1 using the Min-Max feature scaling formula at https://en.wikipedia.org/wiki/Normalization_(statistics) : 

note: scikit-learn provides an API to this: `MinMaxScaler()`

In [ ]:
(student_scores_pd - student_scores_pd.min()) / (student_scores_pd.max() - student_scores_pd.min())

Is it scaling the whole dataset as a single matrix or is it doing the right thing, and scaling each column?

In [ ]:
tmp_df = pd.DataFrame()
for c in student_scores_pd.columns:
    tmp_df[c] = (student_scores_pd[c] - student_scores_pd[c].min()) / (student_scores_pd[c].max() - student_scores_pd[c].min())

In [ ]:
tmp_df

**Question** Why aren't the two datasets different?

### Simple transformations

In [ ]:
student_scores_pd.hist(figsize=(20,10));

In [ ]:
student_scores_pd.plot.scatter(x='Test', y='Extra Credit')

**Exercise** Looks like the `Extra Credit` column in `student_scores_pd` may need to be log scaled. Please do so.

In [ ]:
%%postcell exercise_030_130_a

#type your answer here

### Sort a dataframe

In [ ]:
student_scores_pd

We can sort a table by a column, in either ascending or decending manner

In [ ]:
student_scores_pd.sort_values(by='Test', ascending=False)

In [ ]:
student_scores_pd.sort_values(by=['Test', 'Assignment 1', 'Extra Credit'], ascending=False)

A dataframe can be sorted by index in the following manner:

In [ ]:
student_scores_pd.sort_index()

**Exercise** Sort the dataframe `student_scores_pd` by Extra Credit, then Test scores
(try to guess how multiple columns might be sorted)

In [ ]:
%%postcell exercise_030_130_d

#type your answer here

### 'Bucketize' a column

There are times when you need to convert a 'numeric' column to a category or a factor. For example, client ages may be better represented as the decage of their age (20s, 30s, 40s) or 'young', 'middle age', 'senior.' Algorithms to create such buckets can be quite involved; however, for our purpose, we will use `pd.cut` to divide up values any way pandas likes.

In [ ]:
student_scores_pd

In [ ]:
student_scores_pd['Assignment 1']#.sort_values()

In [ ]:
pd.cut(student_scores_pd['Assignment 1'], bins=3)

In [ ]:
student_scores_example_pd = student_scores_pd.copy()
student_scores_example_pd['Assignment 1 segmented'] = pd.cut(student_scores_pd['Assignment 1'], bins=3)

In [ ]:
student_scores_example_pd

**Exercise** Add the buckets created above to dataframe `student_scores_example_pd` and name the column `Assignment 1 segmented`

In [ ]:
%%postcell exercise_030_130_b

student_scores_example_pd = student_scores_pd.copy()

#type your answer here

student_scores_example_pd

### Convert row values to columns (one-hot-encoding)

Statistical models like logistic regression need 'one-hot-encoded' columns. The following example shows how built-in function can be used, alogn with the knowledge of dataframes we have built-up so far. Note that the sciki-learn library provides a similar function in _OneHotEncoder_.

In [22]:
student_scores_pd['Gender'] = ['Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Female', 'Male', 'Female', 'Private Info']
student_scores_pd

               Assignment 1  Assignment 2   Test  Extra Credit        Gender
Homer                  67.0          68.0   86.0           1.0          Male
Marge                  17.0          78.0  101.0           9.0        Female
Bart                   38.0          41.0  442.0          34.0          Male
Lisa                   44.0          93.0  504.0          70.0        Female
Maggie                 16.0          18.0   35.0           1.0        Female
Jon                    35.0          11.0  142.0           8.0          Male
Arya                   33.0          94.0  988.0          49.0        Female
Ned                    33.0          97.0  381.0           4.0          Male
Danny                   9.0           2.0  621.0          86.0        Female
That red lady          53.0           9.0  361.0          51.0  Private Info

Convert the `Gender` column

In [23]:
student_scores_pd['Gender']

Homer                    Male
Marge                  Female
Bart                     Male
Lisa                   Female
Maggie                 Female
Jon                      Male
Arya                   Female
Ned                      Male
Danny                  Female
That red lady    Private Info
Name: Gender, dtype: object

In [24]:
pd.get_dummies(student_scores_pd['Gender'])

               Female   Male  Private Info
Homer           False   True         False
Marge            True  False         False
Bart            False   True         False
Lisa             True  False         False
Maggie           True  False         False
Jon             False   True         False
Arya             True  False         False
Ned             False   True         False
Danny            True  False         False
That red lady   False  False          True

Combine the orignal datagframe with the new columns (NOTE: we will learn about `concat` in a later lecture)

In [25]:
pd.concat([student_scores_pd, pd.get_dummies(student_scores_pd['Gender'])], axis=1)

,Assignment 1,Assignment 2,Test,Extra Credit,Gender,Female,Male,Private Info
Homer,67.0,68.0,86.0,1.0,Male,False,True,False
Marge,17.0,78.0,101.0,9.0,Female,True,False,False
Bart,38.0,41.0,442.0,34.0,Male,False,True,False
Lisa,44.0,93.0,504.0,70.0,Female,True,False,False
Maggie,16.0,18.0,35.0,1.0,Female,True,False,False
Jon,35.0,11.0,142.0,8.0,Male,False,True,False
Arya,33.0,94.0,988.0,49.0,Female,True,False,False
Ned,33.0,97.0,381.0,4.0,Male,False,True,False
Danny,9.0,2.0,621.0,86.0,Female,True,False,False
That red lady,53.0,9.0,361.0,51.0,Private Info,False,False,True

Looks like we have to remove the `Gender` column ourselves

In [26]:
pd.concat([student_scores_pd, pd.get_dummies(student_scores_pd['Gender'])], axis=1).drop(['Gender'], axis=1)

,Assignment 1,Assignment 2,Test,Extra Credit,Female,Male,Private Info
Homer,67.0,68.0,86.0,1.0,False,True,False
Marge,17.0,78.0,101.0,9.0,True,False,False
Bart,38.0,41.0,442.0,34.0,False,True,False
Lisa,44.0,93.0,504.0,70.0,True,False,False
Maggie,16.0,18.0,35.0,1.0,True,False,False
Jon,35.0,11.0,142.0,8.0,False,True,False
Arya,33.0,94.0,988.0,49.0,True,False,False
Ned,33.0,97.0,381.0,4.0,False,True,False
Danny,9.0,2.0,621.0,86.0,True,False,False
That red lady,53.0,9.0,361.0,51.0,False,False,True

**Exercise** Change the 'Assignment 1 segmented' column in `student_scores_example_pd` to be one-hot-encoded, for consumtpion by a model

In [ ]:
%%postcell exercise_030_130_c

#type your answer here